print("EL producto es numero cuadrado")
print("El producto no es numero cuadrado")
print("EL producto es numero cuadrado")
print("EL producto es numero cuadrado")
print("El producto no es numero cuadrado")
print("EL producto es numero cuadrado")
print("EL producto es numero cuadrado")
print("EL producto es numero cuadrado")
print("EL producto es numero cuadrado")
print("EL producto es numero cuadrado")
print("El producto no es numero cuadrado")
print("EL producto es numero cuadrado")
print("El producto no es numero cuadrado")
print("EL producto es numero cuadrado")
print("EL producto es numero cuadrado")
print("El producto no es numero cuadrado")
